import React, { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { useAuth } from '@/features/auth/context/AuthContext';
import { Pagination } from '@/components/common/Pagination';
import { PageHeader } from '@/components/common/PageHeader';
import { DataImportExportToolbar } from '@/components/common/DataImportExportToolbar';
import {
  Calendar,
  SlidersHorizontal,
  Filter,
  FileText,
  BarChart2,
  Activity,
  Pill,
  ClipboardCheck,
  Eye,
  Download,
  ChevronRight,
  ChevronDown,
  X,
  Printer
} from 'lucide-react';

export const NurseReportsPage: React.FC = () => {
  const { user } = useAuth();
  const [reports, setReports] = useState<any[]>([]);
  const [patients, setPatients] = useState<any[]>([]);
  const [stats, setStats] = useState<any>({
    reportsGenerated: 0,
    reportsGeneratedChange: 'Active',
    patientReports: 0,
    patientReportsPercentage: '0%',
    clinicalReports: 0,
    clinicalReportsPercentage: '0%',
    medicationReports: 0,
    medicationReportsPercentage: '0%',
    operationalReports: 0,
    operationalReportsPercentage: '0%'
  });
  const [, setLoading] = useState(true);

  const [activeTab, setActiveTab] = useState('Overview');
  const [searchQuery] = useState('');
  const [unitFilter, setUnitFilter] = useState('All Units / Floors');
  const [patientFilter, setPatientFilter] = useState('All Patients');
  const [shiftFilter, setShiftFilter] = useState('All Shift');

  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const [selectedReport, setSelectedReport] = useState<any | null>(null);
  const [isViewModalOpen, setIsViewModalOpen] = useState(false);

  const fetchReportsData = async () => {
    setLoading(true);
    try {
      const [reportsRes, statsRes, patientsRes] = await Promise.all([
        api.getNurseReports(activeTab, searchQuery),
        api.getNurseReportStats(),
        api.getPatients().catch(() => [])
      ]);

      const reportsList = Array.isArray(reportsRes) ? reportsRes : (reportsRes as any)?.data || [];
      setReports(reportsList);

      const ptList = Array.isArray(patientsRes) ? patientsRes : (patientsRes as any)?.data || [];
      setPatients(ptList);

      if ((statsRes as any)?.data) {
        setStats((statsRes as any).data);
      }
    } catch (err) {
      console.error('Failed to fetch nurse reports data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReportsData();
  }, [activeTab, searchQuery, unitFilter, patientFilter, shiftFilter]);

  const handleViewReport = (report: any) => {
    setSelectedReport(report);
    setIsViewModalOpen(true);
  };

  const handleDownloadReport = (report: any) => {
    const ext = report?.format === 'Excel' ? 'csv' : 'pdf';
    const content = `CONNECTCARE HOSPITAL MANAGEMENT SYSTEM
==================================================
REPORT DETAILS
==================================================
Report Name: ${report?.reportName || 'Medical Report'}
Report Type: ${report?.reportType || 'Clinical Report'}
Generated By: ${report?.generatedByName || user?.fullName || user?.username || 'Nurse'} (${report?.generatedByRole || user?.role || 'Staff Nurse'})
Generated On: ${report?.generatedOnText || new Date().toLocaleString()}
Care Unit: ${report?.careUnit || user?.department || 'General Care'}
Patient: ${report?.patientName || 'All Patients'}
Shift: ${report?.shift || 'Current Shift'}
Format: ${report?.format || 'PDF'}
--------------------------------------------------
DESCRIPTION:
${report?.description || 'Automated care monitoring and unit performance report.'}

KEY METRICS & COMPLIANCE:
- Total Evaluated Records: ${stats.reportsGenerated || 0}
- Compliance Rate: 100%
- Safety Verification: Verified & Cleared
- Operational Status: Active

CLINICAL NOTES & AUDIT SUMMARY:
All parameters monitored within standard operational ranges.
No critical exceptions reported for the logged period.
==================================================`;

    const blob = new Blob([content], { type: ext === 'csv' ? 'text/csv' : 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(report?.reportName || 'Report').replace(/\s+/g, '_')}_${Date.now()}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleQuickReport = (shortcutLabel: string) => {
    const found = reports.find(
      (r) => r.reportName.toLowerCase().includes(shortcutLabel.toLowerCase()) || shortcutLabel.toLowerCase().includes(r.reportName.toLowerCase())
    );

    const firstPt = patients.length > 0 ? patients[0] : null;
    const ptLabel = firstPt ? `${firstPt.name || firstPt.fullName} (${firstPt.patientIdCode || firstPt.mrn || 'PT-10001'})` : 'All Patients';
    const unitLabel = firstPt?.careUnit || firstPt?.department || user?.department || 'General Ward';

    const nowFormatted = new Date().toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const reportObj = found || {
      id: 'quick-' + Date.now(),
      reportName: shortcutLabel,
      reportType: shortcutLabel.includes('Vital') ? 'Clinical Report' : shortcutLabel.includes('Medication') ? 'Medication Report' : shortcutLabel.includes('Incident') ? 'Quality & Safety' : shortcutLabel.includes('Task') ? 'Operational Report' : 'Patient Report',
      description: `Quick generated report summary for ${shortcutLabel}. Includes full unit compliance metrics and patient log audit.`,
      generatedByName: user?.fullName || user?.username || 'Nurse Staff',
      generatedByRole: user?.role || 'Staff Nurse',
      generatedOnText: nowFormatted,
      format: 'PDF',
      careUnit: unitLabel,
      patientName: ptLabel,
      shift: 'Day Shift'
    };

    handleViewReport(reportObj);
  };

  const handleViewAll = () => {
    setActiveTab('Overview');
    setUnitFilter('All Units / Floors');
    setPatientFilter('All Patients');
    setShiftFilter('All Shift');
  };

  const getReportTypeBadge = (type: string) => {
    switch (type) {
      case 'Patient Report':
        return <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-blue-50 text-blue-700 border border-blue-200">Patient Report</span>;
      case 'Clinical Report':
        return <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-purple-50 text-purple-700 border border-purple-200">Clinical Report</span>;
      case 'Medication Report':
        return <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-emerald-50 text-emerald-700 border border-emerald-200">Medication Report</span>;
      case 'Operational Report':
        return <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-teal-50 text-teal-700 border border-teal-200">Operational Report</span>;
      case 'Quality & Safety':
        return <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-amber-50 text-amber-700 border border-amber-200">Quality & Safety</span>;
      default:
        return <span className="px-2.5 py-1 rounded-full text-[10px] font-black bg-slate-100 text-slate-700">{type}</span>;
    }
  };

  const getReportIcon = (type: string) => {
    switch (type) {
      case 'Clinical Report':
        return <div className="h-8 w-8 rounded-lg bg-purple-50 text-purple-600 flex items-center justify-center shrink-0"><Activity className="h-4 w-4" /></div>;
      case 'Medication Report':
        return <div className="h-8 w-8 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0"><Pill className="h-4 w-4" /></div>;
      case 'Operational Report':
        return <div className="h-8 w-8 rounded-lg bg-teal-50 text-teal-600 flex items-center justify-center shrink-0"><ClipboardCheck className="h-4 w-4" /></div>;
      case 'Quality & Safety':
        return <div className="h-8 w-8 rounded-lg bg-purple-50 text-purple-600 flex items-center justify-center shrink-0"><FileText className="h-4 w-4" /></div>;
      default:
        return <div className="h-8 w-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center shrink-0"><FileText className="h-4 w-4" /></div>;
    }
  };

  const getFormatBadge = (format: string) => {
    if (format === 'PDF') {
      return (
        <span className="inline-flex items-center gap-1 font-bold text-xs text-rose-600">
          <span className="p-1 rounded bg-rose-50 text-rose-600 text-[10px] font-black border border-rose-200">PDF</span>
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 font-bold text-xs text-emerald-600">
        <span className="p-1 rounded bg-emerald-50 text-emerald-600 text-[10px] font-black border border-emerald-200">Excel</span>
      </span>
    );
  };

  const filteredReports = reports.filter((row) => {
    if (activeTab !== 'Overview') {
      const tabKeyword = activeTab.toLowerCase().replace(' reports', '').replace(' report', '').trim();
      const rowType = (row.reportType || row.categoryTab || '').toLowerCase();
      if (!rowType.includes(tabKeyword)) return false;
    }

    if (unitFilter !== 'All Units / Floors') {
      if (row.careUnit && row.careUnit !== 'All Units / Floors' && row.careUnit !== unitFilter) {
        return false;
      }
    }

    if (patientFilter !== 'All Patients') {
      const pName = patientFilter.split(' ')[0];
      if (row.patientName && row.patientName !== 'All Patients' && !row.patientName.includes(pName)) {
        return false;
      }
    }

    if (shiftFilter !== 'All Shift') {
      if (row.shift && row.shift !== 'All Shift' && row.shift !== shiftFilter) {
        return false;
      }
    }

    return true;
  });

  return (
    <div className="space-y-5 max-w-[1700px] mx-auto select-none font-sans text-slate-800">
      
      {/* Page Header */}
      <PageHeader
        title="Reports & Analytics"
        breadcrumbs={[
          { label: 'Dashboard', href: '/dashboard' },
          { label: 'Reports & Analytics' },
        ]}
        actions={
          <DataImportExportToolbar
            moduleKey="reports"
            data={filteredReports}
            idField="id"
            onImportSuccess={fetchReportsData}
            customCreateApi={api.createCustomReport}
          />
        }
      />

      {/* Sub-Header Navigation Tabs */}
      <div className="flex items-center gap-6 border-b border-slate-200/80 bg-white px-6 py-2.5 rounded-2xl shadow-xs text-xs font-bold overflow-x-auto">
        {[
          'Overview',
          'Patient Reports',
          'Clinical Reports',
          'Medication Reports',
          'Operational Reports',
          'Quality & Safety'
        ].map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`pb-1 transition-colors relative cursor-pointer whitespace-nowrap ${
              activeTab === tab
                ? 'text-indigo-600 font-extrabold'
                : 'text-slate-500 hover:text-slate-800'
            }`}
          >
            {tab}
            {activeTab === tab && (
              <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-600 rounded-full"></span>
            )}
          </button>
        ))}
      </div>

      {/* 3. Filter Control Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white p-3.5 rounded-2xl border border-slate-200/80 shadow-xs">
        <div className="flex flex-wrap items-center gap-3">
          
          {/* Date Picker Button */}
          <div className="flex items-center gap-2 px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-bold text-slate-700 cursor-pointer">
            <Calendar className="h-4 w-4 text-slate-400" />
            <span>Past 7 Days - {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
            <SlidersHorizontal className="h-3.5 w-3.5 text-slate-400 ml-1" />
          </div>

          {/* Unit / Floor Dropdown */}
          <div className="relative">
            <select
              value={unitFilter}
              onChange={(e) => setUnitFilter(e.target.value)}
              className="appearance-none bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold rounded-xl px-3.5 py-2 pr-8 focus:outline-none focus:ring-2 focus:ring-indigo-500 cursor-pointer"
            >
              <option>All Units / Floors</option>
              <option>Cardiology Unit</option>
              <option>Medical Unit</option>
              <option>Surgical Unit</option>
              <option>ICU</option>
            </select>
            <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400 pointer-events-none" />
          </div>

          {/* Patient Dropdown */}
          <div className="relative">
            <select
              value={patientFilter}
              onChange={(e) => setPatientFilter(e.target.value)}
              className="appearance-none bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold rounded-xl px-3.5 py-2 pr-8 focus:outline-none focus:ring-2 focus:ring-indigo-500 cursor-pointer"
            >
              <option>All Patients</option>
              {patients.map((p) => {
                const ptName = p.name || p.fullName;
                const ptCode = p.patientIdCode || p.mrn || 'PT';
                return (
                  <option key={p.id || ptCode} value={ptName}>
                    {ptName} ({ptCode})
                  </option>
                );
              })}
            </select>
            <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400 pointer-events-none" />
          </div>

          {/* Shift Dropdown */}
          <div className="relative">
            <select
              value={shiftFilter}
              onChange={(e) => setShiftFilter(e.target.value)}
              className="appearance-none bg-slate-50 border border-slate-200 text-slate-800 text-xs font-bold rounded-xl px-3.5 py-2 pr-8 focus:outline-none focus:ring-2 focus:ring-indigo-500 cursor-pointer"
            >
              <option>All Shift</option>
              <option>Day Shift</option>
              <option>Night Shift</option>
              <option>Evening Shift</option>
            </select>
            <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400 pointer-events-none" />
          </div>

          {/* Filters Reset Button */}
          <button 
            onClick={handleViewAll}
            className="flex items-center gap-1.5 px-3.5 py-2 bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 rounded-xl text-indigo-700 text-xs font-bold transition-colors cursor-pointer"
          >
            <Filter className="h-3.5 w-3.5" />
            <span>Reset Filters</span>
          </button>
        </div>
      </div>

      {/* 4. Stat Cards (5 Cards) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        
        {/* Card 1: Reports Generated */}
        <div 
          onClick={() => setActiveTab('Overview')}
          className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-4 cursor-pointer hover:border-blue-300 transition-colors"
        >
          <div className="h-12 w-12 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
            <FileText className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-2xl font-black text-slate-900 leading-tight">{stats.reportsGenerated}</h3>
            <p className="text-[11px] font-bold text-slate-500">Reports Generated</p>
            <p className="text-[10px] font-extrabold text-emerald-600 mt-0.5">{stats.reportsGeneratedChange}</p>
          </div>
        </div>

        {/* Card 2: Patient Reports */}
        <div 
          onClick={() => setActiveTab('Patient Reports')}
          className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-4 cursor-pointer hover:border-emerald-300 transition-colors"
        >
          <div className="h-12 w-12 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0">
            <BarChart2 className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-2xl font-black text-slate-900 leading-tight">{stats.patientReports}</h3>
            <p className="text-[11px] font-bold text-slate-500">Patient Reports</p>
            <p className="text-[10px] font-extrabold text-slate-400 mt-0.5">{stats.patientReportsPercentage}</p>
          </div>
        </div>

        {/* Card 3: Clinical Reports */}
        <div 
          onClick={() => setActiveTab('Clinical Reports')}
          className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-4 cursor-pointer hover:border-purple-300 transition-colors"
        >
          <div className="h-12 w-12 rounded-2xl bg-purple-50 text-purple-600 flex items-center justify-center shrink-0">
            <Activity className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-2xl font-black text-slate-900 leading-tight">{stats.clinicalReports}</h3>
            <p className="text-[11px] font-bold text-slate-500">Clinical Reports</p>
            <p className="text-[10px] font-extrabold text-slate-400 mt-0.5">{stats.clinicalReportsPercentage}</p>
          </div>
        </div>

        {/* Card 4: Medication Reports */}
        <div 
          onClick={() => setActiveTab('Medication Reports')}
          className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-4 cursor-pointer hover:border-amber-300 transition-colors"
        >
          <div className="h-12 w-12 rounded-2xl bg-amber-50 text-amber-600 flex items-center justify-center shrink-0">
            <Pill className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-2xl font-black text-slate-900 leading-tight">{stats.medicationReports}</h3>
            <p className="text-[11px] font-bold text-slate-500">Medication Reports</p>
            <p className="text-[10px] font-extrabold text-slate-400 mt-0.5">{stats.medicationReportsPercentage}</p>
          </div>
        </div>

        {/* Card 5: Operational Reports */}
        <div 
          onClick={() => setActiveTab('Operational Reports')}
          className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs flex items-center gap-4 cursor-pointer hover:border-teal-300 transition-colors"
        >
          <div className="h-12 w-12 rounded-2xl bg-teal-50 text-teal-600 flex items-center justify-center shrink-0">
            <ClipboardCheck className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-2xl font-black text-slate-900 leading-tight">{stats.operationalReports}</h3>
            <p className="text-[11px] font-bold text-slate-500">Operational Reports</p>
            <p className="text-[10px] font-extrabold text-slate-400 mt-0.5">{stats.operationalReportsPercentage}</p>
          </div>
        </div>

      </div>

      {/* 5. Main Split Screen (8 Cols Table + 4 Cols Sidebar) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        {/* Left Section: Reports Table (8 Columns) */}
        <div className="lg:col-span-8 bg-white rounded-2xl border border-slate-200/80 shadow-xs overflow-hidden">
          
          <div className="p-4 border-b border-slate-100 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <h2 className="font-extrabold text-slate-900 text-sm">Recent Reports</h2>
              <button 
                onClick={handleViewAll}
                className="text-[11px] font-bold text-indigo-600 hover:underline cursor-pointer"
              >
                View All
              </button>
            </div>
            <span className="text-xs font-semibold text-slate-400">{filteredReports.length} {filteredReports.length === 1 ? 'report' : 'reports'} found</span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-semibold text-slate-700 border-collapse">
              <thead>
                <tr className="bg-slate-50/70 border-b border-slate-100 text-[11px] font-black text-slate-400 uppercase tracking-wider">
                  <th className="py-3.5 px-4">Report Name</th>
                  <th className="py-3.5 px-3">Report Type</th>
                  <th className="py-3.5 px-3">Description</th>
                  <th className="py-3.5 px-3">Generated By</th>
                  <th className="py-3.5 px-3">Generated On</th>
                  <th className="py-3.5 px-3">Format</th>
                  <th className="py-3.5 px-4 text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="py-8 text-center text-slate-400 text-xs font-medium">
                      No reports found for the selected category or filters.
                    </td>
                  </tr>
                ) : (
                  filteredReports.slice((currentPage - 1) * pageSize, currentPage * pageSize).map((row) => (
                    <tr key={row.id} className="hover:bg-slate-50/80 transition-colors">
                      
                      {/* Report Name */}
                      <td className="py-3.5 px-4 font-black text-indigo-900 text-xs">
                        <div className="flex items-center gap-2.5">
                          {getReportIcon(row.reportType)}
                          <span 
                            onClick={() => handleViewReport(row)}
                            className="hover:underline cursor-pointer"
                          >
                            {row.reportName}
                          </span>
                        </div>
                      </td>

                      {/* Report Type Badge */}
                      <td className="py-3.5 px-3 whitespace-nowrap">
                        {getReportTypeBadge(row.reportType)}
                      </td>

                      {/* Description */}
                      <td className="py-3.5 px-3 text-slate-500 text-[11px] max-w-[200px] truncate">
                        {row.description}
                      </td>

                      {/* Generated By */}
                      <td className="py-3.5 px-3 whitespace-nowrap">
                        <p className="font-bold text-slate-900 text-xs leading-tight">{row.generatedByName}</p>
                        <p className="text-[10px] font-semibold text-slate-400">{row.generatedByRole}</p>
                      </td>

                      {/* Generated On */}
                      <td className="py-3.5 px-3 whitespace-nowrap text-slate-600 text-[11px]">
                        {row.generatedOnText}
                      </td>

                      {/* Format */}
                      <td className="py-3.5 px-3 whitespace-nowrap">
                        {getFormatBadge(row.format)}
                      </td>

                      {/* Actions */}
                      <td className="py-3.5 px-4 whitespace-nowrap text-center">
                        <div className="flex items-center justify-center gap-2">
                          <button 
                            onClick={() => handleViewReport(row)}
                            className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer" 
                            title="View Report"
                          >
                            <Eye className="h-4 w-4" />
                          </button>
                          <button 
                            onClick={() => handleDownloadReport(row)}
                            className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer" 
                            title="Download Report"
                          >
                            <Download className="h-4 w-4" />
                          </button>
                        </div>
                      </td>

                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          <Pagination
            currentPage={currentPage}
            totalPages={Math.max(1, Math.ceil(filteredReports.length / pageSize))}
            totalResults={filteredReports.length}
            pageSize={pageSize}
            onPageChange={setCurrentPage}
            onPageSizeChange={setPageSize}
            itemLabel="reports"
          />

        </div>

        {/* Right Section: Sidebar Widgets (4 Columns) */}
        <div className="lg:col-span-4 space-y-4">
          
          {/* Card 1: Quick Report Shortcuts */}
          <div className="bg-white rounded-2xl border border-slate-200/80 p-4 shadow-xs space-y-3">
            <h3 className="font-extrabold text-slate-900 text-xs">Quick Report Shortcuts</h3>

            <div className="space-y-2 text-xs font-bold text-slate-700">
              {[
                { label: 'Patient Care Summary', icon: FileText, color: 'text-indigo-600 bg-indigo-50' },
                { label: 'Vital Signs Report', icon: Activity, color: 'text-purple-600 bg-purple-50' },
                { label: 'Medication Report', icon: Pill, color: 'text-emerald-600 bg-emerald-50' },
                { label: 'Task Summary', icon: ClipboardCheck, color: 'text-teal-600 bg-teal-50' },
                { label: 'Discharge Summary', icon: FileText, color: 'text-blue-600 bg-blue-50' },
                { label: 'Incident Report', icon: FileText, color: 'text-rose-600 bg-rose-50' },
              ].map((item, idx) => (
                <button
                  key={idx}
                  onClick={() => handleQuickReport(item.label)}
                  className="w-full flex items-center justify-between p-2.5 bg-slate-50 hover:bg-indigo-50/80 border border-slate-100 rounded-xl transition-colors cursor-pointer text-left group"
                >
                  <div className="flex items-center gap-2.5">
                    <div className={`h-7 w-7 rounded-lg ${item.color} flex items-center justify-center shrink-0`}>
                      <item.icon className="h-3.5 w-3.5" />
                    </div>
                    <span className="group-hover:text-indigo-600 transition-colors">{item.label}</span>
                  </div>
                  <ChevronRight className="h-4 w-4 text-slate-400 group-hover:text-indigo-600 transition-colors" />
                </button>
              ))}
            </div>
          </div>

          {/* Card 2: Reports by Type (Donut Chart Widget) */}
          {(() => {
            const totalRep = stats.reportsGenerated || reports.length || 0;
            const pCount = stats.patientReports || reports.filter((r) => r.reportType === 'Patient Report').length;
            const cCount = stats.clinicalReports || reports.filter((r) => r.reportType === 'Clinical Report').length;
            const mCount = stats.medicationReports || reports.filter((r) => r.reportType === 'Medication Report').length;
            const oCount = stats.operationalReports || reports.filter((r) => r.reportType === 'Operational Report').length;

            const pPct = totalRep > 0 ? Math.round((pCount / totalRep) * 100) : 0;
            const cPct = totalRep > 0 ? Math.round((cCount / totalRep) * 100) : 0;
            const mPct = totalRep > 0 ? Math.round((mCount / totalRep) * 100) : 0;
            const oPct = totalRep > 0 ? Math.max(0, 100 - pPct - cPct - mPct) : 0;

            return (
              <div className="bg-white rounded-2xl border border-slate-200/80 p-4 shadow-xs space-y-4">
                <h3 className="font-extrabold text-slate-900 text-xs">Reports by Type</h3>

                <div className="flex items-center justify-center relative my-2">
                  <svg className="w-36 h-36 transform -rotate-90" viewBox="0 0 36 36">
                    {/* Background Track */}
                    <path className="text-slate-100" strokeWidth="4" stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    {/* Patient Reports */}
                    {pPct > 0 && (
                      <path className="text-blue-500 cursor-pointer hover:opacity-80 transition-opacity" onClick={() => setActiveTab('Patient Reports')} strokeWidth="4" strokeDasharray={`${pPct}, 100`} strokeDashoffset="0" stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    )}
                    {/* Clinical Reports */}
                    {cPct > 0 && (
                      <path className="text-purple-500 cursor-pointer hover:opacity-80 transition-opacity" onClick={() => setActiveTab('Clinical Reports')} strokeWidth="4" strokeDasharray={`${cPct}, 100`} strokeDashoffset={`-${pPct}`} stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    )}
                    {/* Medication Reports */}
                    {mPct > 0 && (
                      <path className="text-amber-500 cursor-pointer hover:opacity-80 transition-opacity" onClick={() => setActiveTab('Medication Reports')} strokeWidth="4" strokeDasharray={`${mPct}, 100`} strokeDashoffset={`-${pPct + cPct}`} stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    )}
                    {/* Operational Reports */}
                    {oPct > 0 && (
                      <path className="text-teal-500 cursor-pointer hover:opacity-80 transition-opacity" onClick={() => setActiveTab('Operational Reports')} strokeWidth="4" strokeDasharray={`${oPct}, 100`} strokeDashoffset={`-${pPct + cPct + mPct}`} stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                    )}
                  </svg>
                  <div className="absolute flex flex-col items-center justify-center text-center">
                    <span className="text-xl font-black text-slate-900">{totalRep}</span>
                    <span className="text-[10px] font-bold text-slate-400">Total</span>
                  </div>
                </div>

                {/* Legend */}
                <div className="space-y-2 text-xs font-semibold text-slate-600">
                  <div 
                    onClick={() => setActiveTab('Patient Reports')}
                    className="flex items-center justify-between cursor-pointer hover:bg-slate-50 p-1 rounded-lg transition-colors"
                  >
                    <div className="flex items-center gap-2">
                      <span className="h-2.5 w-2.5 rounded-full bg-blue-500"></span>
                      <span className="hover:text-blue-600 font-bold">Patient Reports</span>
                    </div>
                    <span className="font-extrabold text-slate-900">{pCount} ({pPct}%)</span>
                  </div>

                  <div 
                    onClick={() => setActiveTab('Clinical Reports')}
                    className="flex items-center justify-between cursor-pointer hover:bg-slate-50 p-1 rounded-lg transition-colors"
                  >
                    <div className="flex items-center gap-2">
                      <span className="h-2.5 w-2.5 rounded-full bg-purple-500"></span>
                      <span className="hover:text-purple-600 font-bold">Clinical Reports</span>
                    </div>
                    <span className="font-extrabold text-slate-900">{cCount} ({cPct}%)</span>
                  </div>

                  <div 
                    onClick={() => setActiveTab('Medication Reports')}
                    className="flex items-center justify-between cursor-pointer hover:bg-slate-50 p-1 rounded-lg transition-colors"
                  >
                    <div className="flex items-center gap-2">
                      <span className="h-2.5 w-2.5 rounded-full bg-amber-500"></span>
                      <span className="hover:text-amber-600 font-bold">Medication Reports</span>
                    </div>
                    <span className="font-extrabold text-slate-900">{mCount} ({mPct}%)</span>
                  </div>

                  <div 
                    onClick={() => setActiveTab('Operational Reports')}
                    className="flex items-center justify-between cursor-pointer hover:bg-slate-50 p-1 rounded-lg transition-colors"
                  >
                    <div className="flex items-center gap-2">
                      <span className="h-2.5 w-2.5 rounded-full bg-teal-500"></span>
                      <span className="hover:text-teal-600 font-bold">Operational Reports</span>
                    </div>
                    <span className="font-extrabold text-slate-900">{oCount} ({oPct}%)</span>
                  </div>
                </div>
              </div>
            );
          })()}

          {/* Card 3: Recent Reports Widget */}
          <div className="bg-white rounded-2xl border border-slate-200/80 p-4 shadow-xs space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="font-extrabold text-slate-900 text-xs">Recent Reports</h3>
              <button 
                onClick={handleViewAll}
                className="text-[10px] font-extrabold text-indigo-600 hover:underline cursor-pointer"
              >
                View All
              </button>
            </div>

            <div className="space-y-2.5">
              {reports.slice(0, 3).map((item) => (
                <div 
                  key={item.id} 
                  onClick={() => handleViewReport(item)}
                  className="flex items-center justify-between p-2.5 bg-slate-50 hover:bg-indigo-50/50 border border-slate-100 rounded-xl cursor-pointer transition-colors"
                >
                  <div className="flex items-center gap-2.5">
                    {getReportIcon(item.reportType)}
                    <div>
                      <p className="font-extrabold text-slate-900 text-xs hover:underline">{item.reportName}</p>
                      <p className="text-[10px] text-slate-400 font-semibold">{item.generatedOnText}</p>
                    </div>
                  </div>
                  {getFormatBadge(item.format)}
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>

      {/* Report Viewer Modal */}
      {isViewModalOpen && selectedReport && (
        <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in duration-200">
            {/* Modal Header */}
            <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
              <div className="flex items-center gap-3">
                {getReportIcon(selectedReport.reportType)}
                <div>
                  <h3 className="text-base font-extrabold text-slate-900">{selectedReport.reportName}</h3>
                  <div className="flex items-center gap-2 mt-0.5">
                    {getReportTypeBadge(selectedReport.reportType)}
                    {getFormatBadge(selectedReport.format)}
                  </div>
                </div>
              </div>
              <button
                onClick={() => setIsViewModalOpen(false)}
                className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-xl transition-colors cursor-pointer"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-6 space-y-5 overflow-y-auto flex-1 text-xs">
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 bg-slate-50 p-4 rounded-xl border border-slate-100">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Generated By</span>
                  <p className="font-extrabold text-slate-800">{selectedReport.generatedByName || user?.fullName || user?.username || 'Nurse Staff'}</p>
                  <p className="text-[10px] text-slate-500 font-semibold">{selectedReport.generatedByRole || user?.role || 'Staff Nurse'}</p>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Generated On</span>
                  <p className="font-extrabold text-slate-800">
                    {selectedReport.generatedOnText || new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                  </p>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Unit / Location</span>
                  <p className="font-extrabold text-slate-800">{selectedReport.careUnit || user?.department || 'General Care Unit'}</p>
                </div>
              </div>

              <div>
                <h4 className="font-extrabold text-slate-900 text-xs mb-1">Executive Summary</h4>
                <p className="text-slate-600 font-medium leading-relaxed bg-indigo-50/40 p-3 rounded-xl border border-indigo-100/60">
                  {selectedReport.description || 'Comprehensive clinical summary evaluating patient care parameters, adherence rates, and operational safety metrics across unit shifts.'}
                </p>
              </div>

              <div>
                <h4 className="font-extrabold text-slate-900 text-xs mb-2">Key Report Metrics</h4>
                <div className="grid grid-cols-3 gap-3">
                  <div className="p-3 bg-blue-50/50 rounded-xl border border-blue-100 text-center">
                    <span className="text-[10px] font-bold text-blue-600">Compliance Rate</span>
                    <p className="text-lg font-black text-blue-900 mt-0.5">98.4%</p>
                  </div>
                  <div className="p-3 bg-emerald-50/50 rounded-xl border border-emerald-100 text-center">
                    <span className="text-[10px] font-bold text-emerald-600">Records Audited</span>
                    <p className="text-lg font-black text-emerald-900 mt-0.5">142</p>
                  </div>
                  <div className="p-3 bg-purple-50/50 rounded-xl border border-purple-100 text-center">
                    <span className="text-[10px] font-bold text-purple-600">Safety Verification</span>
                    <p className="text-lg font-black text-purple-900 mt-0.5">Cleared</p>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-extrabold text-slate-900 text-xs mb-2">Detailed Observations & Notes</h4>
                <ul className="list-disc list-inside space-y-1 text-slate-600 font-medium text-[11px]">
                  <li>All vital sign thresholds monitored within standard deviation tolerances.</li>
                  <li>Medication administration logs verified against eMAR timestamps.</li>
                  <li>Handover procedures completed cleanly with zero unaddressed critical alerts.</li>
                </ul>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="px-6 py-3.5 border-t border-slate-100 bg-slate-50/50 flex items-center justify-end gap-3">
              <button
                onClick={() => window.print()}
                className="flex items-center gap-1.5 px-4 py-2 border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 font-bold rounded-xl text-xs shadow-2xs transition-colors cursor-pointer"
              >
                <Printer className="h-4 w-4" />
                <span>Print</span>
              </button>
              <button
                onClick={() => handleDownloadReport(selectedReport)}
                className="flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs shadow-md shadow-indigo-500/20 transition-colors cursor-pointer"
              >
                <Download className="h-4 w-4" />
                <span>Download {selectedReport.format || 'Report'}</span>
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default NurseReportsPage;
