DELETE FROM chat_messages;
DELETE FROM chat_conversations;
DELETE FROM patient_document_records;
DELETE FROM medication_administrations;
DELETE FROM prescriptions;
DELETE FROM discharge_checklists;
DELETE FROM vital_rounds;
DELETE FROM care_plan_goals;
DELETE FROM care_plans;
DELETE FROM consultations;
DELETE FROM tasks;
DELETE FROM alerts;
DELETE FROM care_team_members;
DELETE FROM care_teams;
DELETE FROM patients;
DELETE FROM doctors;
DELETE FROM nurses;
DELETE FROM user_roles WHERE user_id NOT IN (SELECT id FROM users WHERE username = 'admin');
DELETE FROM users WHERE username != 'admin';
